### ISSUE TITLE
use of free with new

### ISSUE THREAD

**Issue by josemgut** [DataStructuresAlcala/basic-linear-structures-gr6#2]
New should be used with delete, not with free.
Check this information: [http://www.cplusplus.com/forum/beginner/45077/](url)

Solve the problem and answer this issue.

**Comment by IreneGarciaMoreno** [comment]
I have changed free to delete in the main.cpp. Please, let me know if this is correct by now.

**Comment by josemgut** [comment]
Now it is correct. thx
